syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "cap_ble.proto";

option java_package = "hu.alb1.bottle.proto";

message EventLogs {
  string user_id = 1;
  string source_device_id = 2;
  string mobile_device_id = 3;
  repeated ActivationEventLog activation_event_logs = 4;
  repeated FaultEventLog fault_event_logs = 5;
  repeated WaterHistoryEventLog water_history_event_logs = 6;
  repeated WaterFillDrainEventLog water_fill_drain_event_logs = 7;
  repeated FilterEventLog filter_event_logs = 8;
  string source_device_sw_ver = 9;
  string report = 10;
  repeated AdcInfoEventLog adc_act_event_logs = 11;
  repeated AdcInfoEventLog adc_charging_event_logs = 12;
  repeated RateEventLog rate_event_logs = 13;
  string source_event_log_id = 14;
  google.protobuf.Timestamp source_time = 15;
  repeated CapTofLog cap_tof_event_logs = 16;
  repeated CapAdcLog cap_adc_activation_event_logs = 17;
  repeated CapAdcLog cap_adc_charging_event_logs = 18;
  repeated CapActivationLog cap_activation_event_logs = 19;
  repeated CapFaultLog cap_fault_event_logs = 20;
  repeated CapStateLog cap_state_event_logs = 21;
}

message ActivationEventLog {
   google.protobuf.Timestamp ts = 1;
   uint32 mode = 2;
   uint32 pBat = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}

message FaultEventLog {
   google.protobuf.Timestamp ts = 1;
   uint32 code = 2;
   uint32 value = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}

message WaterHistoryEventLog {
   google.protobuf.Timestamp ts = 1;
   repeated float level = 2;
   uint32 source_id = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}

message WaterFillDrainEventLog {
   google.protobuf.Timestamp ts = 1;
   uint32 channel = 2;
   uint32 code = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}

message FilterEventLog {
   google.protobuf.Timestamp ts = 1;
   float volume = 2;
   float totalVolume = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}

message AdcInfoEventLog {
   google.protobuf.Timestamp ts = 1;
   float uvLedVoltageInV = 2;
   float uvLedCurrentInA = 3;
   float uvLedNtcResistanceInOmh = 4;
   float batteryNtcResistanceInOmh = 5;
   float batteryVoltageInV = 6;
   int64 mcuTs = 7;
   int64 shiftTs = 8;
}

message RateEventLog {
   google.protobuf.Timestamp ts = 1;
   float filterRate1 = 2;
   float filterRate2 = 3;
   int64 mcuTs = 4;
   int64 shiftTs = 5;
}