name: bottle
description: "LARQ Bottle BLE companion app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.2.0
  signals: ^6.3.0
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  collection: ^1.18.0
  flutter_health_connect:
    git:
      url: https://github.com/imdzx/flutter_health_connect.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
