name: bottle
description: "LARQ Bottle BLE companion app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.2.0
  signals: ^6.3.0
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.0
  collection: ^1.18.0
  get_it: ^9.2.1
  injectable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.2
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
